name: DTS
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.2.3

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^8.0.0
  http: ^1.2.0
  logger: ^1.0.0
  shared_preferences: ^2.1.0
  cupertino_icons: ^1.0.8
  flutter_map: ^5.0.0
  latlong2: ^0.9.0
  geolocator: ^8.0.0
  search_choices: ^2.0.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.10.0
  flutter_lints: ^4.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/glc.jpg
    - assets/q7.jpg
    - assets/x5.jpg
    - assets/tajikistan_flag.jpg
    - assets/news.jpg

